# Generated by Django 5.1.4 on 2026-04-23 13:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREDIAL', 'Impuesto predial'), ('ARBITRIOS', 'Arbitrios municipales'), ('MULTA', 'Multa administrativa'), ('PAPELETA', 'Papeleta de transito'), ('OTRO', 'Otro concepto')], max_length=20)),
                ('concepto', models.CharField(max_length=200)),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Anio fiscal')),
                ('periodo', models.CharField(blank=True, help_text="Ej: 'Trimestre 1', 'Enero', vacio para anual.", max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VENCIDA', 'Vencida'), ('PAGADA', 'Pagada'), ('FRACCIONADA', 'Fraccionada')], default='PENDIENTE', max_length=20)),
                ('codigo_referencia', models.CharField(max_length=60, unique=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'ordering': ['-anio', 'tipo', 'periodo'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medio', models.CharField(choices=[('CAJA', 'Caja municipal'), ('BANCO', 'Pago en banco'), ('APP', 'Aplicativo movil'), ('WEB', 'Portal web')], default='APP', max_length=10)),
                ('numero_operacion', models.CharField(blank=True, max_length=60)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='deudas.deuda')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
    ]
