# Generated by Django 5.1.4 on 2026-06-16 16:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('prefijo', models.CharField(help_text="Letra(s) para el codigo del turno. Ej: 'P' -> P-045.", max_length=3)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='Color hex para la TV (opcional). Ej: #0B3D91.', max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Servicio (cola)',
                'verbose_name_plural': 'Servicios (colas)',
                'db_table': 'colas_servicio',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, help_text='Dia del turno. La numeracion se reinicia cada dia por servicio.')),
                ('numero', models.IntegerField(help_text='Correlativo por servicio y dia.')),
                ('codigo', models.CharField(help_text='Codigo visible. Ej: P-045.', max_length=12)),
                ('estado', models.CharField(choices=[('EN_ESPERA', 'En espera'), ('LLAMADO', 'Llamado'), ('EN_ATENCION', 'En atención'), ('ATENDIDO', 'Atendido'), ('AUSENTE', 'Ausente (no se presentó)'), ('DERIVADO', 'Derivado'), ('CANCELADO', 'Cancelado')], default='EN_ESPERA', max_length=12)),
                ('prioritario', models.BooleanField(default=False, help_text='Atención preferente (gestante, adulto mayor, discapacidad).')),
                ('canal', models.CharField(choices=[('KIOSKO', 'Kiosko (pantalla táctil)'), ('APP', 'App móvil'), ('MANUAL', 'Manual (asistente)')], default='KIOSKO', max_length=8)),
                ('dni', models.CharField(blank=True, max_length=15)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('cntr_cod', models.IntegerField(blank=True, help_text='CntrCod si se ubico en CONTRIBUYENTES.', null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('llamado_en', models.DateTimeField(blank=True, null=True)),
                ('inicio_atencion_en', models.DateTimeField(blank=True, null=True)),
                ('fin_atencion_en', models.DateTimeField(blank=True, null=True)),
                ('veces_llamado', models.IntegerField(default=0)),
                ('derivado_de', models.ForeignKey(blank=True, help_text='Turno original del que provino esta derivacion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones', to='colas.turno')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_atendidos', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='colas.servicio')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'colas_turno',
                'ordering': ['fecha', 'servicio', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Ventanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nombre', models.CharField(blank=True, help_text="Etiqueta opcional (ej. 'Caja 1').", max_length=80)),
                ('estado', models.CharField(choices=[('CERRADA', 'Cerrada'), ('LIBRE', 'Libre'), ('LLAMANDO', 'Llamando'), ('OCUPADA', 'Ocupada'), ('PAUSA', 'En pausa')], default='CERRADA', max_length=10)),
                ('activa', models.BooleanField(default=True, help_text='Si esta inactiva no aparece en el sistema.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('operador_actual', models.ForeignKey(blank=True, help_text='Usuario (ventanillero) que tiene abierta esta ventanilla.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventanilla_operada', to=settings.AUTH_USER_MODEL)),
                ('servicios', models.ManyToManyField(blank=True, help_text='Que colas atiende esta ventanilla.', related_name='ventanillas', to='colas.servicio')),
                ('turno_actual', models.ForeignKey(blank=True, help_text='Turno que esta llamando / atendiendo ahora.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='colas.turno')),
            ],
            options={
                'verbose_name': 'Ventanilla',
                'verbose_name_plural': 'Ventanillas',
                'db_table': 'colas_ventanilla',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='turno',
            name='ventanilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='colas.ventanilla'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['fecha', 'estado'], name='colas_turno_fecha_e3ed3d_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['dni'], name='colas_turno_dni_8917d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('servicio', 'fecha', 'numero'), name='uniq_turno_servicio_fecha_numero'),
        ),
    ]
