# Generated by Django 5.1.4 on 2026-06-17 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colas', '0002_seed_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='ciudadano',
            field=models.ForeignKey(blank=True, help_text='Usuario del app que saco el turno (si vino por el app).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_colas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turno',
            name='en_cola_desde',
            field=models.DateTimeField(blank=True, help_text="Momento en que entro a la fila ACTIVA. Para walk-in es = creado_en; para reservas del app es el 'Ya llegué'. Se ordena por esto para que la posicion sea justa por llegada, no por hora de reserva.", null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'Reservado (en camino)'), ('EN_ESPERA', 'En espera'), ('LLAMADO', 'Llamado'), ('EN_ATENCION', 'En atención'), ('ATENDIDO', 'Atendido'), ('AUSENTE', 'Ausente (no se presentó)'), ('DERIVADO', 'Derivado'), ('CANCELADO', 'Cancelado')], default='EN_ESPERA', max_length=12),
        ),
    ]
