# Generated by Django 5.1.4 on 2026-04-23 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('siglas', models.CharField(blank=True, max_length=20)),
                ('responsable', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Area municipal',
                'verbose_name_plural': 'Areas municipales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('asunto', models.CharField(max_length=200)),
                ('detalle', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('INGRESADO', 'Ingresado'), ('EN_REVISION', 'En revision'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ARCHIVADO', 'Archivado')], default='INGRESADO', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_estimada', models.DateField(blank=True, null=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('INGRESADO', 'Ingresado'), ('EN_REVISION', 'En revision'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ARCHIVADO', 'Archivado')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos', to='tramites.areamunicipal')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='tramites.expediente')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TipoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('requisitos', models.TextField(blank=True, default='', help_text='Un requisito por linea.')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dias_habiles', models.PositiveSmallIntegerField(default=15, help_text='Plazo maximo segun TUPA.')),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_tramite', to='tramites.areamunicipal')),
            ],
            options={
                'verbose_name': 'Tipo de tramite (TUPA)',
                'verbose_name_plural': 'Tipos de tramite (TUPA)',
                'ordering': ['area', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='tramites.tipotramite'),
        ),
    ]
