# Generated by Django 5.1.4 on 2026-05-12 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadanos', '0002_externos_enlaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='username',
            field=models.CharField(blank=True, help_text='Nombre de usuario para acceder al admin de Django. Vacio para ciudadanos normales — solo lo usan los superusuarios.', max_length=150, null=True, unique=True, verbose_name='Usuario admin'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='dni',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'El DNI debe tener exactamente 8 digitos.')], verbose_name='DNI'),
        ),
    ]
