# Generated by Django 5.1.4 on 2026-04-23 13:13

import apps.tarjetas.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('CULTURA', 'Cultura'), ('DEPORTE', 'Deporte'), ('SALUD', 'Salud'), ('EDUCACION', 'Educacion'), ('RECREO', 'Recreacion'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('lugar', models.CharField(blank=True, max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('gratuito', models.BooleanField(default=True)),
                ('horario', models.CharField(blank=True, max_length=120)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='beneficios/')),
            ],
            options={
                'verbose_name': 'Beneficio',
                'verbose_name_plural': 'Beneficios',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TarjetaCiudadana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=apps.tarjetas.models.generar_codigo_tarjeta, max_length=20, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('bloqueada', models.BooleanField(default=False)),
                ('motivo_bloqueo', models.CharField(blank=True, max_length=200)),
                ('ciudadano', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarjeta ciudadana',
                'verbose_name_plural': 'Tarjetas ciudadanas',
            },
        ),
        migrations.CreateModel(
            name='UsoBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='tarjetas.beneficio')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='tarjetas.tarjetaciudadana')),
            ],
            options={
                'verbose_name': 'Uso de beneficio',
                'verbose_name_plural': 'Usos de beneficios',
                'ordering': ['-fecha'],
            },
        ),
    ]
