# Generated by Django 5.1.4 on 2026-06-03 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BustaCardVentanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cntrcod', models.IntegerField(db_index=True)),
                ('dni', models.CharField(db_index=True, max_length=15)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=30)),
                ('anio', models.IntegerField(help_text='Ejercicio de la tarjeta')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('emitido_por', models.CharField(blank=True, help_text='Usuario administrador que la emitio', max_length=150)),
            ],
            options={
                'verbose_name': 'BustaCard de ventanilla',
                'verbose_name_plural': 'BustaCards de ventanilla',
                'ordering': ['-fecha_emision'],
                'constraints': [models.UniqueConstraint(fields=('cntrcod', 'anio'), name='uniq_bustacard_ventanilla_cntrcod_anio')],
            },
        ),
    ]
