# Generated by Django 5.1.4 on 2026-05-11 19:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gerencia',
                'verbose_name_plural': 'Gerencias',
                'db_table': 'chatbot_gerencia',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConversacionSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_mensaje_en', models.DateTimeField(auto_now=True)),
                ('ciudadano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_chat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesion de conversacion',
                'verbose_name_plural': 'Sesiones de conversacion',
                'db_table': 'chatbot_conversacionsesion',
                'ordering': ['-iniciado_en'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('keywords', models.CharField(blank=True, help_text='Palabras clave separadas por comas (sinonimos, terminos comunes) para mejorar el match en la busqueda.', max_length=500)),
                ('activo', models.BooleanField(default=True)),
                ('veces_consultada', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('gerencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='chatbot.gerencia')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'chatbot_faq',
                'ordering': ['-veces_consultada', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('bot', 'Bot')], max_length=10)),
                ('contenido', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('faq_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='chatbot.faq')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chatbot.conversacionsesion')),
            ],
            options={
                'verbose_name': 'Mensaje de chat',
                'verbose_name_plural': 'Mensajes de chat',
                'db_table': 'chatbot_mensajechat',
                'ordering': ['creado_en'],
            },
        ),
    ]
